//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Produsen_Validasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaporTerimaVaksin
    {
        public int idTer { get; set; }
        public Nullable<int> idLapor { get; set; }
        public string pengirim { get; set; }
        public string deskripsi { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> idVak { get; set; }
    
        public virtual LaporValidasiVaksin LaporValidasiVaksin { get; set; }
        public virtual Vaksin Vaksin { get; set; }
    }
}
