//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CekValid
    {
        public int id { get; set; }
        public Nullable<int> idRegVaksin { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> idPend { get; set; }
        public Nullable<int> idVak { get; set; }
    
        public virtual Data_Penduduk Data_Penduduk { get; set; }
        public virtual Reg_Vaksin Reg_Vaksin { get; set; }
        public virtual Vaksin Vaksin { get; set; }
    }
}
