//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaporValidasiVaksin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaporValidasiVaksin()
        {
            this.LaporTerimaVaksin = new HashSet<LaporTerimaVaksin>();
        }
    
        public int idLapor { get; set; }
        public string namaProdusen { get; set; }
        public string deskripsi { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaporTerimaVaksin> LaporTerimaVaksin { get; set; }
        public virtual Reg_Vaksin Reg_Vaksin { get; set; }
    }
}
