//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Vaksin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reg_Vaksin()
        {
            this.CekValid = new HashSet<CekValid>();
            this.LaporValidasiVaksin = new HashSet<LaporValidasiVaksin>();
            this.PenggunaanVaksin = new HashSet<PenggunaanVaksin>();
            this.ValidasiVaksin = new HashSet<ValidasiVaksin>();
        }
    
        public int id { get; set; }
        public string kode { get; set; }
        public string jenis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CekValid> CekValid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaporValidasiVaksin> LaporValidasiVaksin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PenggunaanVaksin> PenggunaanVaksin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidasiVaksin> ValidasiVaksin { get; set; }
    }
}
