//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidasiVaksin
    {
        public int idVal { get; set; }
        public string namaProdusen { get; set; }
        public string deskripsi { get; set; }
        public Nullable<int> id { get; set; }
        public Nullable<bool> IsValid { get; set; }
    
        public virtual Reg_Vaksin Reg_Vaksin { get; set; }
    }
}
